version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    ports:
      - "${PGSQL_PORT}:${PGSQL_PORT}"
    image: ${PGSQL_NAME}
    container_name: ${PGSQL_NAME}
    environment:
      - PGDATA=${PGSQL_DATA}
      - POSTGRES_DB=${PGSQL_DBNAME}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
  redis:
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
    ports:
      - "${REDIS_PORT}:6379"
    image: ${REDIS_NAME}
    container_name: ${REDIS_NAME}
